services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: devtestuser
      POSTGRES_PASSWORD: devtestpass
      POSTGRES_DB: devtest
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - devtest_network

  redis:
    image: redis:8
    container_name: devtest_redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - devtest_network

  laravel_app:
    container_name: laravel_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www:cached
      - /var/www/node_modules
      - /var/www/vendor
    ports:
      - "5173:5173"
    networks:
      - devtest_network
    depends_on:
      - db
      - redis
    command: ["/var/www/docker/start.sh"]

  nginx:
    image: nginx:alpine
    container_name: devtest_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel_app
    networks:
      - devtest_network

networks:
  devtest_network:
    driver: bridge

volumes:
  db_data:
  redis_data:
